<?PHP
return [
    "Boober",
    "Gobo",
    "Mokey",
    "Red",
    "Wembley",
    "Architect",
    "Crosscut",
    "Crusty",
    "Cotterpin (Architects apprentice)",
    "Flange (Cotterpin's father)",
    "Flex",
    "Hammerhead",
    "Modem (Wrench's mother)",
    "Wrench",
    "Emperor of the Universe",
    "Empress of the Universe",
    "Gunge",
    "Junior",
    "Marjory",
    "Philo",
    "Doc",
    "Sprocket"
];
